packages:
  - 'packages/*'
  - 'playgrounds/*'
  - 'docs'

allowBuilds:
  esbuild: true
  sharp: true
  lmdb: true
  msgpackr-extract: true
  "@parcel/watcher": true
  nx: true
  better-sqlite3: true
  vue-demi: true
